from abc import abstractmethod

class ElectricityGenerator:
    @abstractmethod
    def update(self, date):
        '''Method to update the electricity generated at a specific date'''
        pass

    @abstractmethod
    def getElectricityGenerated():
        '''Method to get the electricity generated by a generator'''
        pass

    @staticmethod
    @abstractmethod
    def generateGenerators(count):
        '''Static method to generate a specific type of generator'''
        pass